<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

// Debian specific: use system-wide library installs for autoloader
// TODO: compose array from information provided by each package
// installing library code under /usr/share/php.
// The following list is only ok for initial tests of the php-composer
// package itself.
return array(
    'Symfony\\Component\\Process\\' => array($vendorDir . '/..'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/..'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/..'),
    'Seld\\JsonLint' => array($vendorDir . '/../Seld/JsonLint'),
    'JsonSchema' => array($vendorDir . '/../JsonSchema'),
    'Composer' => array($baseDir . '/Composer'),
);
